version: '3.9'

services:
  nginx:
    build: ./docker/nginx
    volumes:
      - ./:/opt
    depends_on:
      - php
    ports:
      - "80:80"
  php:
    build: ./docker/php
    environment:
      X_LISTEN: 0.0.0.0:9000
    expose:
      - 9000
    volumes:
      - ./:/opt
    working_dir: /opt
    command: "php public/index.php"
